language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - 'pypy'
  - 'pypy3'
install: pip install -r build_requirements.txt
script:
  - python setup.py sdist
  - python setup.py bdist_wheel
  - flake8 scriba
  - coverage run setup.py test
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: monkeython
  password:
    secure: "UW1o4EiK6yaoAnXjyIFU8hz7Jm8BNSt/U0AZLMSRTfCqpqfNNrsR8dSyHCm4Ht1IEFez4jiOpOaM5HvQfOSIH/h3xCP9mk2v69Ak7X1UGFZjIhZk7Ke7IMpWDUL0OSDXYKndt5c2gkWwfWzS3Ybx75InK2TJZzSwIMDJPMe3YBA="
  on:
    tags: true
    all_branches: true
    repo: monkeython/scriba
